// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type CreateLinkInput struct {
	Title       string `json:"title"`
	Description string `json:"description"`
	ImageURL    string `json:"imageUrl"`
	URL         string `json:"url"`
}

type CreateUserInput struct {
	Email    string `json:"email"`
	Password string `json:"password"`
}
