version: "3.8"
services:
  awesome-links-db:
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=user
      - POSTGRES_DB=awesome-links
    image: postgres:14.1-alpine
    ports:
      - "7001:5432"

  pgadmin:
    environment:
      - PGADMIN_DEFAULT_EMAIL=user@mail.com
      - PGADMIN_DEFAULT_PASSWORD=password
    image: dpage/pgadmin4
    ports:
      - "7101:80"
    depends_on:
      - awesome-links-db
